### PR TITLE
Start to end test

### PR DESCRIPTION
**Pull request by amarkrsinha1997**
The route for complete start to end of the test

### CODE REVIEW

**Comment by amarkrsinha1997** [comment]
Still working on some fixes

**Comment by amarkrsinha1997** [comment]
you can start reviewing this branch

**Comment by RishabhVerma** [comment]
1. There is no point maintaining `exam_config.py` as a different file. Please add it in the `ChanakyaConfig` class defined in `src/config/__init__.py` 

2. When you move the exam_config.py into the main file, it needs to be documented really well about what is the meaning of every part of the config. It requires a lot of guess work to understand it right now.

3. If `QuestionSet` is the model which we use to deal with question sets of 18 questions we need to only deal with them all across our code and not deal with lists of questions as we are doing right now. 

**Example 1:** `get_random_question_set` method on the `Questions` model needs to be a method only used privately by `create_new_set()` method of the `QuestionSet` model instead of being used by the view. 

**Example 2:** `extract_question_set` method of the `EnrolmentKey` model should always return a `QuestionSet` model and not a list of questions. Standardisation FTW xD

4. `get_random_question_set` doesn't have proper documentation of the logic. Please make sure it does.

5. Please make sure we get in a habit of writing detailed docstrings for most of the major functions. We aren't doing it right now. Detail isn't enough right now.

6. In `start_test` method of `EnrolmentKey` model you add the current time with the test duration. Please make sure you add a cushion of at least 20 minutes just to take care of any delays etc.

**Comment by amarkrsinha1997** [comment]
cleared

**Pull request merged**
