### PR TITLE
Questions routes #21

### PR DESCRIPTION
**Pull request by amarkrsinha1997**
Created all the routes as mentioned in the issue #21 and also added all string value in the config file

### CODE REVIEW

**Comment by RishabhVerma** [comment]
Thanks :)

**Comment by RishabhVerma** [comment]
Here are the things which we need to fix in the code:

1. `AWS_BUCKET` is not a good name for a config variable. Make it as `S3_QUESTION_IMAGES_BUCKET`. There should be 3 kinds of buckets which exist on S3. `navgurukulchanakya-dev`, `navgurukulchanakya-prod`, `navgurukulchanakya-staging` and this will change as per config.
2. The key of the file uploaded on AWS currently is the name of the file. I uploaded a file with the name `noun_helping_hand_659885.png` the key in S3 would also become same as the file name. This file will have the URL: `https://s3.ap-south-1.amazonaws.com/navgurukulchanakya/noun_helping_hand_659885.png`. This is a problem as names can be conflicting. You can use the `uuid` module in python to generate unique keys.
3. While both creating and getting questions this should be the format of POST body and also of the response.

```json
{
  "en_text": "Something in English",
  "hi_text": "Something in Hindi",
  "options": [
    {
      "en_text": "",
      "hi_text": "",
      "correct": true
    },
    {
      "en_text": "",
      "hi_text": "",
      "correct": true
    },
    {
      "en_text": "",
      "hi_text": "",
      "correct": false
    },
  ]
}
```

Notice how options is an array and not dictionary/hashmap. This helps us add as many options or as less options. Edit the structure according to the question in which there are no options and only a single correct answer. You can write code for such a validation using `fields.Nested` and `fields.List` properties. You can also define custom validators in `flask-restless`.

**Comment by amarkrsinha1997** [comment]
I am bit confused on which validation are you referencing to write with the ```fields```

**Comment by amarkrsinha1997** [comment]
I am confused in a part what happened is that I have updated a personal_details models which led to creating a new migrations file in that branch but after changing the question model in questions branch a new migration file would be created how will I merge both this migration file?
@RishabhVerma

**Comment by amarkrsinha1997** [comment]
Please review the code @RishabhVerma  and also can you tell I have kept some of api.model objects in the question route itself should it be there or not?

**Comment by RishabhVerma** [comment]
> Please review the code @RishabhVerma and also can you tell I have kept some of api.model objects in the question route itself should it be there or not?

Please let me know which objects are you talking about. You can cite the code here.

**Comment by amarkrsinha1997** [comment]
I was actually talking about that to return the responses I have created some object with fields and @api.marshal_with() function where I had written some of the objects for the response within the route itself is it a better way to write it or should I keep it in a separate file and import it from that file?
@api.model is added in rest plus for creating response model

**Comment by RishabhVerma** [comment]
Please get in a habit of taking examples from your code while asking such questions. Please cite the code you are talking about to give examples.

**Comment by amarkrsinha1997** [comment]
```python
@api.route('/questions/<question_id>')
class SingleQuestion(Resource):
	single_question = api.model('single_question', {
		'error': fields.Boolean(default=False),
		'question_data': fields.Nested(question_obj),
		'message': fields.String
	})

	@api.marshal_with(single_question)
	def get(self, question_id):
		# return a single question
		question = Questions.query.filter_by(id = question_id).first()

		# if question_id is wrong or doesn't exist
		if not question:
			return {
				'error': True,
				'message': "question_id doesn't exist!"
			}

		return {
			'question_data': question
		}
```
Here the code:
```python 


	single_question = api.model('single_question', {
		'error': fields.Boolean(default=False),
		'question_data': fields.Nested(question_obj),
		'message': fields.String
	})

```
I have actually created a `response_objects.py` the file inside the `helpers` method shall I leave this in the route only or should I keep it in the `response_objects.py

**Comment by RishabhVerma** [comment]
1. While uploading a file the extension of the file needs to be returned. If it is not retained it will create problems of rendering in some browsers. Example: `http://chanakya-dev.s3.amazonaws.com/ff1d04f6-31ca-4084-8754-b09d0a03f170` instead of this it should be `http://chanakya-dev.s3.amazonaws.com/ff1d04f6-31ca-4084-8754-b09d0a03f170.jpg`

2. Don't catch exceptions inside your code right now. We will write a catch all at the top so everything can be caught. Second if you are catching exceptions just for logging please make sure that you re-raise them. You hadn't done so in the code of `upload_file_to_s3` in `helpers.file_uploader.py`

3. When I'm creating a question and let's say I add 4 options and mark correct_answer as `[5]` a new question will be created without an exception. Test CURL request is documented below.

```bash
curl -X POST "http://localhost:5000/question/create?hi_question_text=Yeh%20kuch%20text%20hai%20hindi%20mein.&en_question_text=Yeh%20kuch%20text%20hai%20english%20mein.&difficulty=Easy&topic=Topic%202&type=MQC&option_en_text=English%20Option%201&option_en_text=English%20Option%202&option_en_text=English%20Option%203&option_en_text=English%20Option%204&option_hi_text=Hindi%20Option%201&option_hi_text=Hindi%20Option%202&option_hi_text=Hindi%20Option%203&option_hi_text=Hindi%20Option%204&correct_answers=5" -H "accept: application/json"
```

4. Even in a POST request the parameters are not being sent as POST body. They are being sent as GET parameters. Check out the CURL request above to understand this. To make sure they are sent as POST body in JSON make sure we mark `location=json` in the arguments of our parser.

Everything else is fine apart from this.

**Comment by RishabhVerma** [comment]
1. This for loop in this piece of code written in `routes/questions.py` was not intended. Please make sure you test the code before pushing it on github. 

```python
	def post(self):

		#get the values out of the RequestParser
		args = self.create_question_parser.parse_args()

		options_in_en = args.get('option_en_text')
		options_in_hi = args.get('option_hi_text')
		question_type = args.get('type')
		answers = args.get('correct_answers')
		if question_type == 'MCQ':
			for answer_index in answers:
				if len(options_in_en) < int(answer):
					return {
						'error': True,
						'message': 'Answer index in correct'
					}
		question_dict = parse_question_dict(args)

		#create the question
		question = Questions.create_question(question_dict)

		return {'question': question}
```

*“Quality is not an act, it is a habit.”* 

Let's be responsible about the code we push online :)

**Comment by amarkrsinha1997** [comment]
I am thinking to change post_parser of this route with fields validtion as because there I have to place lots of if else to check each and every thing

```python 
	post_parser = reqparse.RequestParser()
	post_parser.add_argument('hi_question_text', type=str, required=True)
	post_parser.add_argument('en_question_text', type=str, required=True)
	post_parser.add_argument('difficulty',type=str, choices=[attr.value for attr in app.config['QUESTION_DIFFICULTY']], required=True)
	post_parser.add_argument('topic',type=str, choices=[attr.value for attr in app.config['QUESTION_TOPIC']], required=True)
	post_parser.add_argument('type',type=str, choices=[attr.value for attr in app.config['QUESTION_TYPE']], required=True)
	post_parser.add_argument('option_en_text', type=str, action='append', required=True, help='options in ENGLISH')
	post_parser.add_argument('option_hi_text', type=str, action='append', required=True, help='options in HINDI')
	post_parser.add_argument('correct_answers', type=str, action='append', required=True, help='Add option number for answer Example: 1 for the first options and same for 2,3,4,...')

	question_create = api.model('question_create', {
		'error':fields.Boolean(default=False),
		'question':fields.Nested(question_obj),
		'message':fields.String
	})

	@api.marshal_with(question_create)
	@api.doc(parser=post_parser)
	def post(self):
```
changing this code to this

```python
# create question
create_option = api.model('create_options',{
    "hi_text": fields.String(required=True),
    "en_text": fields.String(required=True),
    "correct": fields.Boolean(default=False, required=True)
})

create_question = api.model('create_questions',{
    'en_text': fields.String(required=True),
    'hi_text': fields.String(required=True),
    'difficulty': fields.String(enum=[attr.value for attr in app.config['QUESTION_DIFFICULTY']], required=True),
    'topic': fields.String(enum=[attr.value for attr in app.config['QUESTION_TOPIC']], required=True),
    'type': fields.String(enum=[attr.value for attr in app.config['QUESTION_TYPE']], required=True),
    'options': fields.List(fields.Nested(create_option))
})
```

which would be the most preferrable way?
and the required=True is not working with the fields validator

**Comment by amarkrsinha1997** [comment]
it worked actually needed to add another parameter ```python validate=True``` in ```python @api.expect(create_question , validate=True)```

**Comment by amarkrsinha1997** [comment]
This route is completly tested

**Comment by RishabhVerma** [comment]
> it worked actually needed to add another parameter validate=True in @api.expect(create_question , validate=True)

Yes it is. But let's do that in the next version. Abhi sahi hai.

**Comment by RishabhVerma** [comment]
Everything is good. Just a few minor changes. As we are following REST, **`GET /question`** should give us a list of questions, **`POST /question`** should create a question and **GET /question/<id> should give us a the question with a particular ID.**

Also there is a PUT endpoint missing right now. This would mean we cannot edit the questions. Please also add a **`PUT /questions/<id>` to edit the questions.**

Also I've made some changes int the naming scheme of Route classes in `routes/questions.py` Check them out.

**Comment by amarkrsinha1997** [comment]
For updating each question we will assume that each question which needs to be updated would contain id and all the option in it will also contain an id with itself so it will not cause the problem when we will delete any options which were like 
when we delete an option for a question every time it would not be deleted as when a student attempts a question the id of the question along with the options which he had selected get saves in the attempts table so if we delete options of the question we won't be able to calculate the marks of the student who had attempted that question in future after creating a new options

**Comment by amarkrsinha1997** [comment]
the logic to update a question:
Update each question by query it to the database and then update each option according to the id that has been provided. where I will get options id attached with the question.
what if a user adds a new option in that table? shall I create a new option record for the new one? @RishabhVerma

**Comment by amarkrsinha1997** [comment]
for updating option we also have to check are the ids correct or not

**Comment by amarkrsinha1997** [comment]
cleared

**Comment by RishabhVerma** [comment]
1. Please make sure every function you are making which can't be understood by another developer in less than 2minutes should have a docstring with it.

2. In the `PUT /question/<id>` request, I should also be able to create new options which would mean I am passing an option object without an ID. That is not considered right now.

**Comment by amarkrsinha1997** [comment]
This branch is completely tested and documented properly you can go ahead and review it @RishabhVerma

**Pull request merged**
