### PR TITLE
MD Parser for Inserting New Questions

### PR DESCRIPTION
**Pull request by amarkrsinha1997**
Created new question parser with a standard MD format in which question should be written with choices

### CODE REVIEW

**Comment by RishabhVerma** [comment]
Please make sure we are using the question creation API to create questions when we are inserting questions into the DB.

**Comment by RishabhVerma** [comment]
> Please make sure we are using the question creation API to create questions when we are inserting questions into the DB.

Have you implemented this?

**Comment by amarkrsinha1997** [comment]
Should I add something for storing the options in this branch? @RishabhVerma

**Comment by amarkrsinha1997** [comment]
cleared

**Comment by amarkrsinha1997** [comment]
Implemented the logic for updating a newly added option and storing it id to the file as follow
whenever we add a new option it's id should contain NULL value and when we added it to the platform 
the response will have the id of the newly added options which will not be in the existing file we will iterate over each option id and will check is this id present in the file or not if not then we will add it to the first option who's value is NULL. @RishabhVerma

**Comment by amarkrsinha1997** [comment]
This branch is completed with proper documentation you can go ahead and review it @RishabhVerma

**Pull request closed without merging**
