### PR TITLE
Personal details

### PR DESCRIPTION
**Pull request by amarkrsinha1997**
created and documented the personal_details route please review this route #20

### CODE REVIEW

**Comment by RishabhVerma** [comment]
I'm facing this issue while trying to test out the branch.

```bash
flask.cli.NoAppException: While importing "chanakya.src", an ImportError was raised:

Traceback (most recent call last):
  File "/Users/rishabhverma/.venv/chanakya/lib/python3.7/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/Users/rishabhverma/NavGurukul/chanakya/src/__init__.py", line 25, in <module>
    from chanakya.src.routes import *
  File "/Users/rishabhverma/NavGurukul/chanakya/src/routes/__init__.py", line 2, in <module>
    from .test import *
  File "/Users/rishabhverma/NavGurukul/chanakya/src/routes/test.py", line 8, in <module>
    from chanakya.src.helpers.routes_description import VALIDATE_ENROLMENT_KEY_DESCRIPTION,PERSONAL_DETAILS_DESCRIPTION
ModuleNotFoundError: No module named 'chanakya.src.helpers.routes_description'
```

**Comment by RishabhVerma** [comment]
Can you test this out completely and give me a green signal to test it out.

**Comment by amarkrsinha1997** [comment]
This branch is completely tested now
@RishabhVerma

**Comment by RishabhVerma** [comment]
Thanks! I will check it in the evening.

**Comment by RishabhVerma** [comment]
**`POST /test/personal_details`** still takes in all the parameters as GET parameters and not as JSON. Please make so that a JSON payload can be sent to the request.

**Comment by amarkrsinha1997** [comment]
cleared

**Pull request merged**
